repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        - id: check-yaml
        - id: check-docstring-first
        - id: check-merge-conflict
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.0.0
      hooks:
      - id: autoflake
        name: Remove unused variables and imports
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
            "--ignore-pass-after-docstring",
          ]
        files: \.py$
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          args: ["--profile", "black"]
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
      - id: black
        name: Black Python code formatting
        language: python
        types: [python]
        args: ["--line-length=88"]
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
        - id: nbstripout